isEmpty(QSERIENJUNKIES_PATH) {
    error(You have to set QSERIENJUNKIES_PATH to the path of QSERIENJUNKIES)
}

QSERIENJUNKIES_TARGET           = qserienjunkies
QSERIENJUNKIES_VERSION          = 0.0.0
QSERIENJUNKIES_INCLUDEPATH      = $$PWD/src
QSERIENJUNKIES_LIBS             = -L$$QSERIENJUNKIES_PATH/src -l$$QSERIENJUNKIES_TARGET
